services:
  backend:
    networks:
      - interview-net
    build: ./BackEnd
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd:/app
    env_file:
      - ./BackEnd/.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - redis

  frontend:
    networks:
      - interview-net
    build: ./FrontEnd
    ports:
      - "3000:3000"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  redis:
    image: redis:latest
    networks:
      - interview-net
    ports:
      - "6379:6379"

networks:
  interview-net:
    driver: bridge